# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banishment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ban_reason', models.CharField(help_text=b'Reason for the ban?', max_length=255)),
                ('type', models.CharField(choices=[(b'ip-address', b'IP Address'), (b'user-agent', b'User Agent')], default=0, help_text=b'Type of User Ban to store', max_length=20)),
                ('condition', models.CharField(help_text=b'Some descriptive text goes here', max_length=255)),
            ],
            options={
                'db_table': 'banishments',
                'verbose_name': 'Banishments',
                'verbose_name_plural': 'Banishments',
                'permissions': (('can_ban_user', 'Can Ban User'),),
            },
        ),
    ]
