# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_reason', models.CharField(help_text=b'Reason for the whitelist?', max_length=255)),
                ('type', models.CharField(choices=[(b'ip-address-whitelist', b'Whitelist IP Address')], default=0, help_text=b'Enter an IP address to whitelist', max_length=20)),
                ('condition', models.CharField(help_text=b'Enter an IP to whitelist', max_length=255)),
            ],
            options={
                'db_table': 'whitelists',
                'verbose_name': 'Whitelist',
                'verbose_name_plural': 'Whitelists',
                'permissions': (('can_whitelist_user', 'Can Whitelist User'),),
            },
        ),
        migrations.AlterModelOptions(
            name='banishment',
            options={'permissions': (('can_ban_user', 'Can Ban User'),), 'verbose_name': 'Banishment', 'verbose_name_plural': 'Banishments'},
        ),
        migrations.AlterField(
            model_name='banishment',
            name='condition',
            field=models.CharField(help_text=b'Enter an IP to ban/whitelist, or a User Agent string to ban', max_length=255),
        ),
        migrations.AlterField(
            model_name='banishment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
